# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe2111ccf3f0182b0fda69c1be989423adb5de9e280bad6f53f81ba0af6c95583cb9364651c92c495b3d800d8ced043388e64ba446fd9ed722f45a9f7dfe420d

test:
  secret_key_base: 441119ea20b27f00a384df304318a2959b72472cf4ef2cd2b9ac0f6b54bed343b76e04ba0bfb1bb5c1cdcf08bcd852fdf12f30e009c37dfb4d8740cecb3635bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
